// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi4FWh_0ZxORxBJaE60WlhS3oCjAQ1CyI',
    appId: '1:954693952578:web:8a90a2d379611c32beb9db',
    messagingSenderId: '954693952578',
    projectId: 'booking-room-tristart',
    authDomain: 'booking-room-tristart.firebaseapp.com',
    storageBucket: 'booking-room-tristart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAve_6KhxATLofPirfHiITiBPPm3VVDOJ8',
    appId: '1:954693952578:android:8c0238826ebe9558beb9db',
    messagingSenderId: '954693952578',
    projectId: 'booking-room-tristart',
    storageBucket: 'booking-room-tristart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjU5hV_QnI_VQiZO1JKxD_0m6X5kqJsQ4',
    appId: '1:954693952578:ios:e823873570618211beb9db',
    messagingSenderId: '954693952578',
    projectId: 'booking-room-tristart',
    storageBucket: 'booking-room-tristart.firebasestorage.app',
    iosBundleId: 'com.example.bookingRoom',
  );
}
